### ISSUE TITLE
[Regression 0.2.4] Mixing RegExps and strings in include array is broken

### ISSUE THREAD

**Issue by dschmidt** [broccolijs/broccoli-funnel#32]
Hey,

since 0.2.4 it's not possible anymore to mix strings and regexps in the include option:

```javascript
var Funnel = require('broccoli-funnel');

module.exports = new Funnel('foobar/', {
  include:  [
    'index.html',
    /\.js$/,
    /\.map$/,
    /\.css$/
  ]
});
```
This code works in 0.2.3 but fails in 0.2.4 with this error:
```
TypeError: undefined is not a function
    at MatcherCollection.match (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/node_modules/walk-sync-matcher/may-match.js:13:26)
    at MatcherCollection.mayContain (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/node_modules/walk-sync-matcher/may-match.js:38:12)
    at walkSync (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/node_modules/walk-sync-matcher/index.js:19:15)
    at Funnel.processFilters (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/index.js:125:15)
    at Funnel.build (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/index.js:114:10)
    at /home/domme/dev/sources/foobar/node_modules/broccoli-funnel/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/domme/dev/sources/foobar/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1198:9)

Build failed
```

BR,
Domme

**Comment by rwjblue** [comment]
Thanks for reporting.

@stefanpenner - Thoughts?

**Comment by stefanpenner** [comment]
likely do to my work. I'll fix.

@dschmidt if you move everything over to globs, it will work better.

**Comment by dschmidt** [comment]
@stefanpenner globs as in '*.css' etc?

**Comment by stefanpenner** [comment]
@dschmidt thanks for the bug report, will be fixed with 0.2.5

**Comment by stefanpenner** [comment]
@dschmidt releases as 0.2.5

**Comment by dschmidt** [comment]
Thanks :+1: (already switched to globs tho)
